config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  root "tasks#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category].blank?
      @tasks = Task.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category])
      @tasks = Task.where(category_id: @category_id).order("created_at DESC")
    end
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(tasks_params)

    if @task.save
      redirect_to @task
    else
      render "New"
    end
  end

  def edit
  end

  def update
    if @task.update(tasks_params)
      redirect_to @task
    else
      render "Edit"
    end
  end

  def destroy
    @task.destroy
    redirect_to root_path
  end

  private

  def tasks_params
    params.require(:task).permit(:title, :description, :company, :url, :category_id)
  end

  def find_task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
  %title TaskRabbit
  = stylesheet_link_tag    'application', media: 'all'
  = javascript_include_tag 'application'
  = csrf_meta_tags

%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand TaskRabbit
      %ul.nav.navbar-nav
        %li= link_to "All Tasks", root_path
        - Category.all.each do |category|
          %li= link_to category.name, tasks_path(category: category.name)
      = link_to "New Task", new_task_path, class: "navbar-text navbar-right navbar-link"

  .container
    .col-md-8.col-md-offset-2
      = yield

app/views/tasks/_form.html.haml
= simple_form_for(@task, html: { class: 'form_horizontal'}) do |f|
  = f.collection_select :category_id, Category.all, :id, :name, { prompt: "Choose a Category" }, input_html: { class: "dropdown-toggle" }
  = f.input :title, label: "Task Title", input_html: { class: "form-control" }
  = f.input :description, label: "Task Description", input_html: { class: "form-control" }
  = f.input :company, label: "Your Company", input_html: { class: "form-control" }
  = f.input :url, label: "Link to Task", input_html: { class: "form-control" }
  %br/
  = f.button :submit

app/views/tasks/edit.html.haml
%h1 Edit Task

=render 'form'

= link_to "Back", root_path

app/views/tasks/index.html.haml
#jobs
  - @tasks.each do |task|
    .job
      %h2= link_to task.title, task
      %p= task.company

app/views/tasks/new.html.haml
%h1 New Task

=render 'form'

= link_to "Back", root_path

app/views/tasks/show.html.haml
#jobs
  .job
    %h1= @task.title
    %p= @task.description
    %p= @task.company
    %button.btn.btn-default= link_to "Complete Task", @task.url

#links
  = link_to "Home", root_path, class: "btn btm-sm btn-default"
  = link_to "Edit", edit_task_path(@task), class: "btn btm-sm btn-default"
  = link_to "Delete", task_path(@task), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-default"